import time

print('Ready for some jokes? Press "Enter" to continue.')
input()
print('What do you get when you cross a snowman with a vampire?')
input()
print('Frostbite!')
print()
time.sleep(1)
print('What do dentists call an astronaut\'s cavity?')
input()
print('A black hole!')
print()
time.sleep(1)
print('Knock, knock.')
input()
print("Who's there?")
input()
print('Interrupting cow.')
input()
print('Interrupting cow wh', end='')
print('-MOO!')
