---
- name: My playbook
  hosts: localhost
  connection: local
  gather_facts: False

  tasks:
    - name: "Roll default die the default number of times!"
      dice_module:
      register: dice_results
    - debug:
        var: dice_results

    - name: "Roll a custom d15 die 5 times"
      dice_module:
        dice_side_number: 6
        number_of_rolls: 20
      register: dice_results
    - debug:
        var: dice_results

    - name: "Run addition module"
      sum_module:
        number_one: 3
        number_two: 5
      register: sum_results
    - debug:
        var: sum_results

    - name: "Scrape the Hacker News API"
      hn_top_stories:
        number_of_entries: 20
      register: top_stories
    - debug:
        var: top_stories
