[package]
name = "guessing_game"
version = "0.1.0"
edition = "2021"

[lib]
name = "guessing_game"
crate-type = ["cdylib"]

[dependencies]
rand = "0.8.3"
pyo3 = { version = "0.17.1", features = ["extension-module"] }
